"""init tables

Revision ID: 1af7bd2f0fa4
Revises: c659655bcdc9
Create Date: 2026-08-19 03:06:47.445955

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1af7bd2f0fa4"
down_revision: Union[str, Sequence[str], None] = "c659655bcdc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("meaaage", sa.Column("message_id", sa.Integer(), nullable=False))
    op.drop_column("meaaage", "messeg_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meaaage",
        sa.Column("messeg_id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.drop_column("meaaage", "message_id")
    # ### end Alembic commands ###
