"""change user_id to bigint

Revision ID: 61b96fdf8316
Revises: 1af7bd2f0fa4
Create Date: 2026-08-19 03:36:48.711794

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "61b96fdf8316"
down_revision: Union[str, Sequence[str], None] = "1af7bd2f0fa4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("message_id"),
    )
    op.drop_table("meaaage")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meaaage",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("message_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_table("message")
    # ### end Alembic commands ###
